project:
  type: website

website:
  title: "Chuyi Sun"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: data_analysis.qmd
        text: Data analysis

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

